// Generated by CoffeeScript 1.4.0
var loader;

loader = new Shotgun.Loader({
  url: {
    js: 'js/testapp.js?' + Math.random(),
    css: 'css/testapp.css?' + Math.random()
  },
  functions: [
    function(cb) {
      return window.app = new window.Testapp({
        callback: cb
      });
    }, function(cb) {
      return window.app.fun1(cb);
    }, function(cb) {
      return window.app.fun2(cb);
    }
  ],
  ready: function() {
    return window.app.ready();
  }
});

$(document).ready(function() {
  return loader.start();
});
