// Generated by CoffeeScript 1.4.0
var loader;

loader = new Shotgun.Loader({
  urls: {
    libs: ['http://underscorejs.org/underscore-min.js', 'http://backbonejs.org/backbone-min.js'],
    apps: ['/js/testapp.js']
  },
  debug: true,
  data: function(cb) {
    console.log('some data');
    return cb();
  },
  ready: function(data) {
    return Testapp(data);
  }
});

$(document).ready(function() {
  return loader.start();
});
